version: '3'

services:
  web:
    container_name: wordpress_web
    image: wordpress:latest
    ports:
      - 8087:80

    depends_on:
      - db
  db:
    container_name: wordpress_db
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    image: 2034/phpmyadmin
    container_name: wordpress_phpmyadmin
    depends_on:
      - db
    ports:
      - 9006:80
    environment:
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
volumes:
    db_data: {}
