#echo -n 'hello' | base64
#aGVsbG8=
apiVersion: v1
kind: Secret
metadata:
  name: secret-wordpress
type: Opaque
data:
  MYSQL_PASSWORD: d29yZHByZXNz
  MYSQL_ROOT_PASSWORD: c29tZXdvcmRwcmVzcw==
        
